name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: install dependencies
        working-directory: 03-implementing-solid/api-node-SOLID
        run: npm ci

      - name: run tests
        working-directory: 03-implementing-solid/api-node-SOLID
        run: npm run test